#! /bin/bash

# i3wm-personal-defaults, a set of files for Debian systems which use the i3 window manager.
#
# Copyright (C) 2024, 2025 Wojciech Zduniak <githubinquiries.ladder140@passinbox.com>
#
# This file is part of i3wm-personal-defaults
#
# i3wm-personal-defaults is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# i3wm-personal-defaults is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with i3wm-personal-defaults.  If not, see <https://www.gnu.org/licenses/>.

cat <<EOF >&2
i3wm-personal-defaults, a set of files for Debian systems which use the i3 window manager.

Copyright (C) 2024, 2025 Wojciech Zduniak <githubinquiries.ladder140@passinbox.com>

This file is part of i3wm-personal-defaults

i3wm-personal-defaults is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
i3wm-personal-defaults is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with i3wm-personal-defaults.  If not, see <https://www.gnu.org/licenses/>.

Current sink volume is:

EOF

RESULT=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)

if [ "$?" -ne 0 ]; then
	echo "ERROR"
	exit 1
elif [ "$RESULT" == "0%" ]; then
	echo "MUTED"
else
	echo "$RESULT"
fi
